.TH TODO 1
.SH NAME
todo \- manage todo lists from the command line
.SH SYNOPSIS
.B todo
[\fB\-\-version\fR]
[\fB\-h|\-\-help\fR]
[\fB\-q|\-\-quiet\fR]
[\fB\-\-file\-name \fIfilename\fR]
.I <command>
.IB <args...>
.SH DESCRIPTION
.B todo
is a command-line utility for creating and modifying todo lists.
.SH OPTIONS
.TP
.B \-\-version
Prints the version and exits.
.TP
.B \-h ", " \-\-help
Displays help information.
.TP
.B \-q ", " \-\-quiet
Suppress output, unless no command is given.
.TP
.B \-f ", " \-\-file\-name =\fIfilename\fR
.SH AUTHORS
Eduardo Antunes dos Santos Vieira <eduardoantunes986@gmail.com>
.SH COPYRIGHT
Copyright Eduardo Antunes dos Santos Vieira 2022. Licensed under GNU GPL version 3.
