.TH TODO 1
.\"
.SH NAME
todo \- manage todo lists from the command line
.\"
.SH SYNOPSIS
.B todo [options] [command] [<args>...]
.\"
.SH DESCRIPTION
.\"
.B todo
is a command-line utility for managing todo lists. It is simple and small: all it
allows one to do is to create tasks, remove them and change their state. There are
only three valid states: todo, done and in-progress.
.PP
When it is run, it checks the current directory for a TODO file, creating it if
it does not exist. That file is used by it to record the todo list for that 
directory. It is possible to make 
.B todo 
search for a different filename, as described further in this page.
.PP
Available commands:
.TP 2
•
.I add
.TP 2
•
.I check
.TP 2
•
.I help
.TP 2
•
.I rm
.TP 2
•
.I uncheck
.TP 2
•
.I work-on
.PP
All of these commands may be called by providing just their first letter. So todo
will interpret a lonely "w" as a "work-on" command, and a "c" as a "check".
.PP
After carrying out the operation of a command,
.B todo
will print the list to stdout. Each task is printed to its own line, containing
its index, state and name. The todo state is shown as an empty box; the done state
is shown as a box filled with a check symbol or an X; and the in-progress state 
is shown as box filled with a dash. If no command is given, the list will also be
printed in this fashion.
.\"
.SH OPTIONS
.TP 2
.B \-\-version
Print version number and copyright and exit.
.\"
.TP 2
.B \-h, \-\-help
If a command was given, show the usage text for it. Otherwise, show the general usage text.
.\"
.TP 2
.B \-q, \-\-quiet
Suppress output, unless no command is given or an error occurs.
.\"
.TP 2
.B \-f, \-\-file\-name=\fIfilename\fR
Change the name of the file used for saving the todo list.
.\"
.SH ENVIRONMENT VARIABLES
.TP 2
.B TODO_ASCII_ONLY
Use only ascii characters to display the todo list.
.TP 2
.B TODO_FILENAME
Change the name of the file used for saving the todo list.
.\"
.TP 2
.B TODO_QUIET
Suppress output, unless no command is given or an error occurs.
.\"
.SH COMMANDS
.SS Add Command
The add command takes a series of task names and appends them to the end of the
todo list, marked as "todo".
.\"
.SS Check Command
The check command takes a series of task indices and marks the tasks they 
correspond to as done.
.\"
.SS Help Command
The help command may take the name of a command as an argument. In this case, it
will show the usage text for that particular command. If the given argument does
not correspond to a command or no argument is given, then it shows the general
usage text.
.\"
.SS Rm Command
The rm command takes a series of task indices and removes the tasks they correspond
to from the list.
.\"
.SS Uncheck Command
The uncheck command takes a series of task indices and marks the tasks they 
correspond to as todo.
.\"
.SS Work-on Command
The work-on command takes a series of task indices. It marks all but the last task 
they correspond to as done. The last one is marked as in-progress. This is due to
the principle that there should be only one in-progress task at any given moment.
Another consequence of it is that, if there was already an in-progress task on
the list when this command is called, it will be marked as done.
.\"
.SH AUTHORS
Eduardo Antunes dos Santos Vieira <eduardoantunes986@gmail.com>
.\"
.SH COPYRIGHT
Copyright 2022 Eduardo Antunes dos Santos Vieira.
.\"
.SH LICENSING
todo is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation,
either version 3 of the License, or (at your option)
any later version.
.PP
todo is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more
details.
.PP
You should have received a copy of the GNU General
Public License along with todo. If not, see
<https://www.gnu.org/licenses/>.
